apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-templating
  namespace: openshift-gitops
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-templating
    spec:
      version: v1.0
      generate:
        command:
          - /bin/argocd-templating-client
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-templating-token-creator
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts/token
    verbs:
      - create
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
      - watch
      - update
      - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-templating-token-creator
subjects:
  - kind: ServiceAccount
    name: default
    namespace: openshift-gitops
roleRef:
  kind: ClusterRole
  name: argocd-templating-token-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  sourceNamespaces:
    - my-app
  server:
    route:
      enabled: true
  repo:
    sidecarContainers:
      - name: argocd-templating
        image: quay.io/mprahl/argocd-templating-plugin:latest
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: argocd-templating-tmp
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: plugin.yaml
            name: argocd-templating
          - name: argocd-templating-token-sa
            mountPath: /var/run/secrets/kubernetes.io/serviceaccount
            readOnly: true
    volumes:
      - configMap:
          name: argocd-templating
        name: argocd-templating
      - emptyDir: {}
        name: argocd-templating-tmp
      - name: argocd-templating-token-sa
        projected:
          sources:
            - serviceAccountToken:
                expirationSeconds: 3600
                path: token
            - configMap:
                items:
                  - key: ca.crt
                    path: ca.crt
                name: kube-root-ca.crt
