// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: templaterequest/template_request.proto

package templaterequest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TemplateResolver_Resolve_FullMethodName = "/templaterequest.TemplateResolver/Resolve"
)

// TemplateResolverClient is the client API for TemplateResolver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TemplateResolverClient interface {
	Resolve(ctx context.Context, in *TemplateRequest, opts ...grpc.CallOption) (*TemplateResponse, error)
}

type templateResolverClient struct {
	cc grpc.ClientConnInterface
}

func NewTemplateResolverClient(cc grpc.ClientConnInterface) TemplateResolverClient {
	return &templateResolverClient{cc}
}

func (c *templateResolverClient) Resolve(ctx context.Context, in *TemplateRequest, opts ...grpc.CallOption) (*TemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateResponse)
	err := c.cc.Invoke(ctx, TemplateResolver_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemplateResolverServer is the server API for TemplateResolver service.
// All implementations must embed UnimplementedTemplateResolverServer
// for forward compatibility.
type TemplateResolverServer interface {
	Resolve(context.Context, *TemplateRequest) (*TemplateResponse, error)
	mustEmbedUnimplementedTemplateResolverServer()
}

// UnimplementedTemplateResolverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTemplateResolverServer struct{}

func (UnimplementedTemplateResolverServer) Resolve(context.Context, *TemplateRequest) (*TemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedTemplateResolverServer) mustEmbedUnimplementedTemplateResolverServer() {}
func (UnimplementedTemplateResolverServer) testEmbeddedByValue()                          {}

// UnsafeTemplateResolverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemplateResolverServer will
// result in compilation errors.
type UnsafeTemplateResolverServer interface {
	mustEmbedUnimplementedTemplateResolverServer()
}

func RegisterTemplateResolverServer(s grpc.ServiceRegistrar, srv TemplateResolverServer) {
	// If the following call pancis, it indicates UnimplementedTemplateResolverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TemplateResolver_ServiceDesc, srv)
}

func _TemplateResolver_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateResolverServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateResolver_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateResolverServer).Resolve(ctx, req.(*TemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TemplateResolver_ServiceDesc is the grpc.ServiceDesc for TemplateResolver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TemplateResolver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "templaterequest.TemplateResolver",
	HandlerType: (*TemplateResolverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Resolve",
			Handler:    _TemplateResolver_Resolve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "templaterequest/template_request.proto",
}
